### ISSUE TITLE
Trigger more then one job in chain

### ISSUE THREAD

**Issue by marekkapowicki** [4finance/jenkins-pipeline-dsl#10]
I need the new functionality to trigger two or more jobs in one publish block
In jenkins it is easy to achieve -> we can add list of comma separated jobs to trigger like below 

```
<hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
     <projects>
         project1,project2
     </projects>
</hudson.plugins.parameterizedtrigger.BuildTriggerConfig>
```

The solution can be used to prepare trees (not only chaines) 
the invocation in dsl could like like below
        <code>.then(manual(JOB1, JOB2))</code>
It is not so easy to implement 
 In my opinion ManualLink (and other JobChainLink) can contain list of JobRef as to field (now to is single JobRef). But there is a big change so I would like to spleak before I start implementing it

Artur do you have any ideas how to fix my issue?

**Comment by ArturGajowy** [comment]
The use case you're mentioning (triggering multiple downstream jobs) has been foreseen and is possible without any library changes :) There are two ways to do that:

# 1. Have multiple job chains

This allows for describing arbitrary job trees; DAGs would be possible after adding support for some kind of 'join' (as in fork/join) plugin). So if you wanted a pipeline like this:

```
A -> B -> C -> D -> E -> F
 \ -> G -> H    \ -> I -> J
```

you'd express it like that

``` groovy
pipelineBuilder.configure {
  //declare jobs
  //(...)
  //declare chains
  chain(JobChain.of(A).then(B).then(C).then(D).then(E).then(F))
  chain(JobChain.of(A).then(G).then(H))
  chain(JobChain.of(D).then(I).then(J))
}

//.then(B) is a shorthand for .then(auto(B))
```

This approach is more general and thus more complex. It is only necessary if the 'other chain' is longer than one link. Otherwise, use the preferred and simpler approach:

# 2. Use the `CombinedJobChainLink.of` method

if JOB2 does not to trigger any further jobs. Kudos to @tulinski for inventing it :) Example usage is available [here](https://github.com/4finance/sample-jenkins-microservice-pipeline/blob/master/src/main/groovy/io/fourfinanceit/pipeline/example/MicroservicePipelineTemplate.groovy#L74).

Let me know if that solves your issue :) Remember that any additional chain with a single `.then` step can be replaced by use of a `CombinedJobChainLink`. Be sure to talk with @tulinski if you need more detail on that :)

**Comment by ArturGajowy** [comment]
Also, one thing worth knowing is that the underlying XML will consist of two `BuildTriggerConfig`s (one for project1 and one for project2) and not of a single trigger for both of them (as in the xml example you provided). This should not make a huge difference. The only one I can think of is two entries in the job config's GUI - but I think job-dsl was invented so that we don't have to look there anymore :)

**Comment by marekkapowicki** [comment]
Tkank Artur
I started from CombinedJobChainLink.of - but there is not exactly what I need
I have thought about this issue and i will make some simple PR asap

**Comment by ArturGajowy** [comment]
@marekkapowicki maybe it'd be easier for us to actually talk your use case through face-to-face than to communicate it through sample solutions in code? :) Have you tried the '1. multiple chains' approach?

**Comment by marekkapowicki** [comment]
now i m testing 'multi chains' aproach - it seems to work fine 
So probably i will use it as finall solution

**Comment by marekkapowicki** [comment]
better way to solve described issue is fix bug in jenkins plugins
and then everything works fine without changes in our pipeline-dsl
